### PR TITLE
Update to GLFW 3.3

### PR DESCRIPTION
**Pull request by RobLoach**
https://github.com/vulkan-go/glfw

### CODE REVIEW

**Comment by kivutar** [comment]
It looks like there is a dependency on Vulkan (MoltenVK on OSX).
Can we have glfw 3.3 without this dependency?

**Comment by RobLoach** [comment]
Hmmm, good call. Going to close this one for now.

**Comment by kivutar** [comment]
If you have some time, you can generate an OSX binary for me, and I will try to run it here without MoltenVK installed. And we will know if it's a runtime dependency.

**Comment by RobLoach** [comment]
On Linux, so tried the following, without success...


```
$ GOOS=darwin go build
video.go:18:2: build constraints exclude all Go files in /home/rob/.gocode/src/github.com/go-gl/gl/all-core/gl
go-playthemall.go:10:2: build constraints exclude all Go files in /home/rob/.gocode/src/github.com/go-gl/glfw/v3.2/glfw
core.go:10:2: build constraints exclude all Go files in /home/rob/.gocode/src/github.com/kivutar/go-playthemall/libretro
```

**Comment by RobLoach** [comment]
```
$ CGO_ENABLED=1 GOOS=darwin go build
# golang.org/x/mobile/exp/audio/al
../../../golang.org/x/mobile/exp/audio/al/al_notandroid.go:19:10: fatal error: OpenAL/al.h: No such file or directory
 #include <OpenAL/al.h>
          ^~~~~~~~~~~~~
compilation terminated.
# github.com/go-gl/glfw/v3.2/glfw
gcc: error trying to exec 'cc1obj': execvp: No such file or directory
# os/user
/usr/lib/go-1.10/src/os/user/getgrouplist_darwin.go: In function ‘mygetgrouplist’:
/usr/lib/go-1.10/src/os/user/getgrouplist_darwin.go:14:11: warning: implicit declaration of function ‘getgrouplist’; did you mean ‘mygetgrouplist’? [-Wimplicit-function-declaration]
  int rv = getgrouplist(user, (int) group, buf, ngroups);
           ^~~~~~~~~~~~
           mygetgrouplist
# github.com/go-gl/gl/all-core/gl
../../go-gl/gl/all-core/gl/procaddr.go: In function 'GlowGetProcAddress_glcoreall':
../../go-gl/gl/all-core/gl/procaddr.go:48:16: error: 'RTLD_DEFAULT' undeclared (first use in this function); did you mean 'RTLD_LOCAL'?
   return dlsym(RTLD_DEFAULT, name);
                ^~~~~~~~~~~~
                RTLD_LOCAL
../../go-gl/gl/all-core/gl/procaddr.go:48:16: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by RobLoach** [comment]
```
$ sudo apt-get install gobjc++ -y
$ CGO_ENABLED=1 GOOS=darwin go build              
# os/user
/usr/lib/go-1.10/src/os/user/getgrouplist_darwin.go: In function ‘mygetgrouplist’:
/usr/lib/go-1.10/src/os/user/getgrouplist_darwin.go:14:11: warning: implicit declaration of function ‘getgrouplist’; did you mean ‘mygetgrouplist’? [-Wimplicit-function-declaration]
  int rv = getgrouplist(user, (int) group, buf, ngroups);
           ^~~~~~~~~~~~
           mygetgrouplist
# golang.org/x/mobile/exp/audio/al
../../../golang.org/x/mobile/exp/audio/al/al_notandroid.go:19:10: fatal error: OpenAL/al.h: No such file or directory
 #include <OpenAL/al.h>
          ^~~~~~~~~~~~~
compilation terminated.
# github.com/go-gl/glfw/v3.2/glfw
In file included from ./glfw/src/internal.h:165:0,
                 from ./glfw/src/context.c:28,
                 from ../../go-gl/glfw/v3.2/glfw/c_glfw.go:4:
./glfw/src/cocoa_platform.h:34:9: fatal error: Carbon/Carbon.h: No such file or directory
 #import <Carbon/Carbon.h>
         ^~~~~~~~~~~~~~~~~
compilation terminated.
# github.com/go-gl/gl/all-core/gl
../../go-gl/gl/all-core/gl/procaddr.go: In function 'GlowGetProcAddress_glcoreall':
../../go-gl/gl/all-core/gl/procaddr.go:48:16: error: 'RTLD_DEFAULT' undeclared (first use in this function); did you mean 'RTLD_LOCAL'?
   return dlsym(RTLD_DEFAULT, name);
                ^~~~~~~~~~~~
                RTLD_LOCAL
../../go-gl/gl/all-core/gl/procaddr.go:48:16: note: each undeclared identifier is reported only once for each function it appears in
```

May need a Dockerfile instead, to ease managing the dependencies across the platforms.

**Comment by kivutar** [comment]
Ok, I was thinking that you had an OSX machine.

You can't cross compile CGO projects.

There is a project called xgo however that does the docker thing for you.

**Comment by andydotxyz** [comment]
xgo/docker is not the only way - if you have the right c compiler (for the target platform) installed you can just pass CGO_ENABLED=1 to the build command and it should work...

**Pull request closed without merging**
